samples: '/home/snr28/project/pgcoe/rsv/testdata/test_samples.txt'
readdir: '/home/snr28/project/pgcoe/rsv/testdata/'
runname: 'rsvtest'
refs: '../refs/'
primers: '../primers'
outdir: 'results' 
maxfq_gb: 1