import os
import sys

configfile: "config/config.yaml"
include:    "rules/common.py"
container:  "docker://sethnr/pgcoe_bacseq:0.01"


SAMPLES = [line.strip() for line in open(config['samples'], 'r')]
TARGETS = [line.strip() for line in open(config['refs'], 'r')]


print(":".join(SAMPLES),file=sys.stderr)
print(":".join(TARGETS),file=sys.stderr)

wildcard_constraints:
    sample="[^-]+",
    target="[^\-/]+"


rule all:
    input:
        mallcalls='results/mash/all-calls.txt',
        depths=lambda _: expand('results/align/{target}-depthwins.txt',target=get_valid_targets() ),
        ivar=lambda _: expand("results/ivar/{target}-summary.txt",target=get_valid_targets() ),
        bcf=lambda _: expand("results/bcftools/{target}-summary.txt",target=get_valid_targets() ),
        #depths=expand("results/align/{target}-depths.txt",target=TARGETS )
        #expand('results/summary/{target}_{site}_covpc.tsv',
        #       target=TARGETS, site=["primers"])





include: "rules/mash.smk"

include: "rules/bwa_align.smk"

include: "rules/ivar.smk"

include: "rules/bcf_call.smk"



rule depthplots:
    input:
        dhists=lambda wildcards: expand('results/align/{sample}-{{target}}-depthhist.txt',sample=get_mash_samples(wildcards)),
        dwins=lambda wildcards: expand('results/align/{sample}-{{target}}-depthwins.txt',sample=get_mash_samples(wildcards)),
    output:
        dwins='results/align/{target}-depthwins.txt',
        dhists='results/align/{target}-depthhists.txt',
    resources:
        mem_mb=8000,
        runtime=180,
    log:
        stderr="logs/depth/{target}-depths.err"
    container: "docker://sethnr/pgcoe_analysis:0.01"
    shell:
        """
        cat {input.dhists} > {output.dhists}
        cat {input.dwins} > {output.dwins}
        """




rule get_div_metrics:
    input:
        pileupvcf='results/bcftools/{target}-filt.vcf.gz',
        depth='results/align/{target}-depths.txt',
        primers=os.path.join(config['refsdir']+'{target}.bed'),
        #amplicons='data/{target}.insert.bed',
    output:
        expand('results/summary/{{target}}-{site}-{metric}.tsv',
               site=["primers"],metric=["meandp","covpc","pi"]),
    container: "docker://sethnr/pgcoe_analysis:0.01"
    params:
        ppprefix='results/summary/{target}-primer-stats',
        paprefix='results/summary/{target}-amplicon-stats',
    shell:
        """
        python scripts/get_pidp_ranges.py --vcf {input.pileupvcf} --depth {input.depth} --bed {input.primers} --out {params.ppprefix}
        """

rule get_ivar_report:
    input:
        ivariants=lambda wildcards: expand('results/ivar/{sample}-{{target}}-ivariants.tsv',sample=get_mash_samples(wildcards)),
        iconsensus=lambda wildcards: expand('results/ivar/{sample}-{{target}}-consensus.fa',sample=get_mash_samples(wildcards)),
    output:
        report='results/ivar/{target}-summary.txt'
    shell:
        """
        touch {output.report}
        """

rule get_genotyping_report:
    input:
        ivariants='results/bcftools/{target}-all.vcf.gz',
    output:
        report='results/bcftools/{target}-summary.txt'
    shell:
        """
        touch {output.report}
        """



# rule evorha:
#     input:
#         bam='results/align/{sample}_{target}.bam',
#         idx='results/align/{sample}_{target}.bam.bai',
#     params:
#         ref=config['reference'],
#         bamln='results/evorha/{sample}_sorted.bam',
#         idxln='results/evorha/{sample}_sorted.bam.bai',
#         prefix='results/evorha/',
#     resources:
#         mem_mb=8000,
#         runtime=1440,
#     container: "docker://sethnr/pgcoe_evorha:0.01"
#     output:
#         coreout = 'results/evorha/{sample}.hapfreq',
#     log:
#         stderr="logs/evorha/{sample}.err",
#     message: "Running evorha"
#     shell:
#         """
#           ln -f {input.bam} {params.bamln}
#             ln -f {input.idx} {params.idxln}
#             java -jar /jars/evorha.jar completeAnalysis {params.ref} {params.bamln} 2>&1 >> {log.stderr}
#         """




# rule summary:
#     input:
#         bams = lambda wildcards: expand("results/bams/{{sample}}.{target}.bam",target=get_mash_calls(wildcards)),
#         mashcalls = "results/mash/{sample}_calls.txt",
#     output:
#         individual_all_virustype_info = "/results/align/{sample}_all_virustype_info.txt"
#     log:
#         log = "logs/summary.log"
#     params:
#         summary_script="scripts/write_summary.py
#     resources:
#         partition="day",
#         mem_mb="40G",
#         cpus_per_task=4,
#         runtime=300
#     container: "docker://sethnr/pgcoe_anypipe:0.01"
#     shell:"""
#         {params.summary_script}  -c {input.mashcalls}  -p {params.primer_dir} \
#                 -n {wildcards.sample} -s {params.python_script} \
#                 -e {params.python_script2} -d {params.depth} -t {params.threshold} \
#                 -C {resources.cpus_per_task} -I {params.indir} -O {params.outdir} -L {log.log} \
#                  >> {log.log} 2>&1


